// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.30;

import { Transceiver } from "wormhole-ntt/Transceiver/Transceiver.sol";
import { ManagerBase } from "wormhole-ntt/NttManager/ManagerBase.sol";
import { TransceiverStructs } from "wormhole-ntt/libraries/TransceiverStructs.sol";
import { toWormholeFormat } from "wormhole-solidity-sdk/Utils.sol";
import { TWO_OF_TWO_FLAG } from "./BlockRootOracle.sol";
import { ICommitmentValidator } from "./interfaces/ICommitmentValidator.sol";
import { IRiscZeroVerifier } from "./interfaces/IRiscZeroVerifier.sol";
import { Steel, Encoding as SteelEncoding } from "@steel/contracts/Steel.sol";

/// @dev Prefix for all TransceiverMessage payloads bytes4(keccak256("BoundlessTransceiverPayload"))
bytes4 constant BOUNDLESS_TRANSCEIVER_PAYLOAD_PREFIX = 0x1d49a45d;

contract BoundlessTransceiver is Transceiver {
    /// @notice Struct representing a record of a supported source chain that this
    /// transceiver knows how to validate commitments and event inclusions from.
    struct AuthorizedSource {
        /// @notice Wormhole formatted address of the transceiver contract on the source chain (that emits the
        /// messages).
        bytes32 transceiverContract;
        /// @notice Contract on this chain that can validate Steel commitments from the source chain.
        address commitmentValidator;
        /// @notice Image ID for the program to prove deposit events into the transceiver on this source.
        bytes32 imageID;
    }

    /// @notice The RISC Zero verifier contract used to verify the ZK proof.
    /// @dev This verifier is used to validate the zero-knowledge proofs generated by the guest program.
    IRiscZeroVerifier public verifier;

    /// @notice Map from [Wormhole chain ID](https://wormhole.com/docs/products/reference/chain-ids/)
    /// @notice to contract that will be used to verify the Steel commitments from the foreign chain.
    /// @dev This mapping stores the authorized sources for each chain, including the transceiver contract address,
    /// commitment validator, and image ID needed for verification.
    mapping(uint16 chainId => AuthorizedSource) public authorizedSources;

    /// @notice Map from Wormhole chain ID to the quoted delivery price for messages to that chain.
    /// @dev This mapping stores the delivery prices for each chain, though currently not actively used.
    mapping(uint16 chainId => uint256 quoteDeliveryPrice) public deliveryPrices;

    /// @notice Flag indicating whether relayers are enabled to submit messages with fees.
    /// @dev When true, relayers can submit messages with attached fees. When false, only zero-value transactions are
    /// accepted.
    bool public relayerEnabled;

    /// @notice Journal that is committed to by the guest.
    /// @dev This struct contains all the data needed to verify a ZK proof of a message inclusion.
    struct Journal {
        /// @notice Commitment locks this proof to a specific block root
        /// which can be verified against the blockRootOracle contract.
        Steel.Commitment commitment;
        /// @notice The encoded TransceiverMessage that this proof commits to.
        bytes encodedMessage;
        /// @notice Wormhole formatted address of the contract that emitted the message event.
        bytes32 emitterContract;
    }

    /// @notice Emitted when a message is sent from this transceiver to initiate a cross-chain transfer.
    /// @param recipientChain The Wormhole chain ID of the recipient chain.
    /// @param encodedMessage The encoded TransceiverMessage that will be processed by the relayer.
    event SendTransceiverMessage(uint16 indexed recipientChain, bytes encodedMessage);

    /// @notice Emitted when an authorized source is updated for a specific chain.
    /// @param chainId The Wormhole chain ID of the source chain.
    /// @param transceiverContract The Wormhole formatted address of the transceiver contract on the source chain.
    /// @param validator The commitment validator contract address for the source chain.
    /// @param imageID The image ID for the program to prove deposit events.
    event UpdateAuthorizedSource(
        uint16 indexed chainId, bytes32 indexed transceiverContract, address indexed validator, bytes32 imageID
    );

    /// @notice Emitted when the relayer enabled status is updated.
    /// @param relayerEnabled The new status of the relayer enablement.
    event UpdateRelayerEnabled(bool relayerEnabled);

    /// @notice Error thrown when a source chain is not authorized for message processing.
    /// @param chainId The unsupported chain ID.
    error UnsupportedSourceChain(uint256 chainId);

    /// @notice Error thrown when relayer functionality is used but not enabled.
    error RelayerUnsupported();

    /// @notice Error thrown when a commitment validation fails.
    error InvalidCommitment();

    /// @notice Error thrown when an emitter contract address doesn't match authorized sources.
    error InvalidEmitter();

    constructor(address manager) Transceiver(manager) { }

    /// @notice Initializes a new BoundlessTransceiver.
    /// @param verifier_ The address of the Risc0 verifier deployment on this chain (ideally Risc0VerifierRouter)
    function initialize(address verifier_) external initializer {
        super._initialize();
        verifier = IRiscZeroVerifier(verifier_);
        relayerEnabled = false;
    }

    function getTransceiverType() external view virtual override returns (string memory) {
        return "boundless";
    }

    /// @notice Internal function to send a message to a recipient chain.
    /// @param recipientChain The Wormhole chain ID of the recipient chain.
    /// @param caller The address of the caller initiating the transfer.
    /// @param recipientNttManagerAddress The address of the NTT manager on the recipient chain.
    /// @param nttManagerMessage The message from the NTT manager to be sent.
    /// @dev This function builds and emits a transceiver message that will be picked up by a relayer
    /// to generate a ZK proof of inclusion in the source chain. Note that deliveryPayment, refundAddress,
    /// and transceiverInstruction parameters are part of the interface but not used in Boundless implementation.
    function _sendMessage(
        uint16 recipientChain,
        uint256, // deliveryPayment
        address caller,
        bytes32 recipientNttManagerAddress,
        bytes32, // refundAddress,
        TransceiverStructs.TransceiverInstruction memory, // transceiverInstruction,
        bytes memory nttManagerMessage
    )
        internal
        override
    {
        require(msg.value == 0 || relayerEnabled, RelayerUnsupported());

        (, bytes memory encodedTransceiverPayload) = TransceiverStructs.buildAndEncodeTransceiverMessage(
            BOUNDLESS_TRANSCEIVER_PAYLOAD_PREFIX,
            toWormholeFormat(caller),
            recipientNttManagerAddress,
            nttManagerMessage,
            _encodePayload(ManagerBase(nttManager).chainId())
        );

        // This is the event that the relayer is listening for and will build a ZK
        // proof of its inclusion in the source chain on the destination chain
        emit SendTransceiverMessage(recipientChain, encodedTransceiverPayload);
    }

    function _quoteDeliveryPrice(
        uint16 targetChain,
        TransceiverStructs.TransceiverInstruction memory // transceiverInstruction
    )
        internal
        view
        override
        returns (uint256)
    {
        return deliveryPrices[targetChain]; // Relayer fees are not processed at this time
    }

    /// @notice Process a message along with its ZK proof of inclusion in the origin chain.
    /// @param journalData The journal data that the proof commits to, containing the commitment and encoded message.
    /// @param seal The opaque ZK proof seal that allows it to be verified on-chain.
    /// @dev This function verifies the ZK proof, checks the commitments against authorized sources,
    /// then forwards the validated message to the NTT Manager for processing.
    /// The verification process includes:
    /// 1. Decoding the journal data to extract the commitment and message
    /// 2. Validating the source chain is authorized
    /// 3. Verifying the commitment against the trusted beacon block root
    /// 4. Verifying the ZK proof using the RISC Zero verifier
    /// 5. Delivering the message to the NTT Manager if all checks pass
    function receiveMessage(bytes calldata journalData, bytes calldata seal) external {
        Journal memory journal = abi.decode(journalData, (Journal));
        (
            TransceiverStructs.TransceiverMessage memory parsedTransceiverMessage,
            TransceiverStructs.NttManagerMessage memory parsedNttManagerMessage
        ) = TransceiverStructs.parseTransceiverAndNttManagerMessage(
            BOUNDLESS_TRANSCEIVER_PAYLOAD_PREFIX, journal.encodedMessage
        );

        uint16 sourceChainId = _decodePayload(parsedTransceiverMessage.transceiverPayload);

        // Validate the source chain against authorized sources and the journal
        AuthorizedSource memory source = authorizedSources[sourceChainId];
        require(source.commitmentValidator != address(0), UnsupportedSourceChain(sourceChainId));
        require(source.transceiverContract == journal.emitterContract, InvalidEmitter());

        // validate steel commitment against a trusted beacon block root from the commitment validator for the source
        // chain
        require(
            ICommitmentValidator(source.commitmentValidator).validateCommitment(journal.commitment, TWO_OF_TWO_FLAG),
            InvalidCommitment()
        );

        // Verify the ZK proof
        bytes32 journalHash = sha256(journalData);
        verifier.verify(seal, source.imageID, journalHash);

        // If all prior checks have passed we can trust the ZK proof of an event emitted on the source chain
        // was included and then finalized by the chain. It can be passed to the NTT Manager.
        _deliverToNttManager(
            sourceChainId,
            parsedTransceiverMessage.sourceNttManagerAddress,
            toWormholeFormat(nttManager),
            parsedNttManagerMessage
        );
    }

    /// @notice Sets the commitment validator and source chain transceiverContract for a given Wormhole chain ID.
    /// @param chainId The Wormhole chain ID for which to set the authorized source.
    /// @param transceiverContract The Wormhole formatted address of the transceiver contract on the source chain.
    /// @param validator The commitment validator contract address to use for validating Steel commitments.
    /// @param imageID The image ID for the program to prove deposit events into the transceiver on this source.
    /// @dev Only callable by the contract owner. This function updates the authorized source configuration
    /// which is used to validate incoming messages from the specified chain.
    function setAuthorizedSource(
        uint16 chainId,
        bytes32 transceiverContract,
        address validator,
        bytes32 imageID
    )
        external
        onlyOwner
    {
        authorizedSources[chainId] = AuthorizedSource({
            transceiverContract: transceiverContract,
            commitmentValidator: validator,
            imageID: imageID
        });

        emit UpdateAuthorizedSource(chainId, transceiverContract, validator, imageID);
    }

    /// @notice Sets the relayer enabled status for this transceiver.
    /// @param enabled The new status for relayer enablement.
    /// @dev Only callable by the contract owner. When enabled, relayers can submit messages
    /// with attached fees. When disabled, only zero-value transactions are accepted.
    function setRelayerEnabled(bool enabled) external onlyOwner {
        relayerEnabled = enabled;
        emit UpdateRelayerEnabled(enabled);
    }

    /// @notice Encodes a chain ID into a bytes payload for transceiver messages.
    /// @param chainId The chain ID to encode.
    /// @return payload The encoded chain ID as bytes.
    /// @dev This function packs the chain ID into bytes for inclusion in transceiver messages.
    /// The encoding uses ABI encoding to ensure consistent serialization across chains.
    function _encodePayload(uint16 chainId) internal pure returns (bytes memory payload) {
        payload = abi.encodePacked(chainId);
    }

    /// @notice Decodes a chain ID from a bytes payload.
    /// @param payload The bytes payload containing an encoded chain ID.
    /// @return chainId The decoded chain ID.
    /// @dev This function extracts the chain ID from the payload using inline assembly.
    /// It shifts the loaded value right by 240 bits to extract the 16-bit chain ID.
    function _decodePayload(bytes memory payload) internal pure returns (uint16 chainId) {
        assembly {
            chainId := shr(240, mload(add(payload, 32)))
        }
    }
}
